spring:
  datasource:
    url: jdbc:h2:mem:fintechdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

whatsapp:
  verify-token: test123
  access-token: CHANGE_ME
  phone-id: CHANGE_ME

openai:
  api-key: CHANGE_ME
